version: '3.1'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
        MYSQL_DATABASE: test
        MYSQL_USER: testuser
        MYSQL_PASSWORD: testpassword
        MYSQL_ROOT_PASSWORD: testroot

